# Generated by Django 2.2.2 on 2019-06-08 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190608_1122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogContent',
        ),
    ]
