# Generated by Django 2.2.2 on 2019-06-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190609_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
