# Generated by Django 2.2.2 on 2019-06-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
