# Generated by Django 2.2.2 on 2019-06-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20190613_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='author',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='hot',
            name='author',
            field=models.CharField(max_length=15),
        ),
    ]
